# Generated by Django 2.1.4 on 2021-05-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksAndAuthors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
