# Generated by Django 2.2 on 2021-05-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksAndAuthors', '0002_auto_20210519_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
